const roster = {
  Row1: [
    {
      name: `Mario`,
      series: ["Super Mario Bros"],
      img: `https://ssb.wiki.gallery/images/thumb/e/e1/Mario_SSB4.png/1200px-Mario_SSB4.png`,
      price: 5.0,
      properties: [`Projectiles`, `All`],
    },
    {
      name: `Donkey Kong`,
      series: ["Super Mario Bros", "Donkey Kong"],
      img: `https://ssb.wiki.gallery/images/thumb/c/c9/Donkey_Kong_SSBU.png/1200px-Donkey_Kong_SSBU.png`,
      price: 50.0,
      properties: [`Heavy`, `Ding Dong`, `All`],
    },
    {
      name: `Link`,
      series: ["Legend of Zelda"],
      img: `https://ssb.wiki.gallery/images/thumb/8/84/Link_SSBU.png/1200px-Link_SSBU.png`,
      price: 5.0,
      properties: [`Projectiles`, `All`],
    },
    {
      name: `Samus`,
      series: [`Metroid`],
      img: `https://ssb.wiki.gallery/images/thumb/0/03/Samus_SSBU.png/1200px-Samus_SSBU.png`,
      price: 30.0,
      properties: [`Projectiles`, `All`],
    },
    {
      name: `Dark Samus`,
      series: [`Metroid`],
      img: `https://ssb.wiki.gallery/images/thumb/a/a6/Dark_Samus_SSBU.png/1200px-Dark_Samus_SSBU.png`,
      price: 25.0,
      properties: [`Projectiles`, `All`],
    },
    {
      name: `Yoshi`,
      series: ["Super Mario Bros", "Yoshi's Island"],
      img: `https://ssb.wiki.gallery/images/thumb/8/8d/Yoshi_SSBU.png/1200px-Yoshi_SSBU.png`,
      price: 1000000,
      properties: [`Floaty`, `Projectiles`, `All`],
    },
    {
      name: `Kirby`,
      series: [`Triple Deluxe`],
      img: `https://ssb.wiki.gallery/images/thumb/0/07/Kirby_SSBU.png/1200px-Kirby_SSBU.png`,
      price: 999.0,
      properties: [`Floaty`, `Best Boi`, `All`],
    },
    {
      name: `Fox`,
      series: [`Starfox`],
      img: `https://ssb.wiki.gallery/images/thumb/2/2f/Fox_SSBU.png/1200px-Fox_SSBU.png`,
      price: 20.0,
      properties: [`Light`, `Projectiles`, `All`],
    },
    {
      name: `Pikachu`,
      series: [`Pokemon`],
      img: `https://ssb.wiki.gallery/images/thumb/9/93/Pikachu_SSBU.png/1200px-Pikachu_SSBU.png`,
      price: 35.0,
      properties: [`Projectiles`, `All`],
    },
    {
      name: `Luigi`,
      series: ["Super Mario Bros"],
      img: `https://ssb.wiki.gallery/images/thumb/b/bb/Luigi_SSBU.png/1200px-Luigi_SSBU.png`,
      price: 25.0,
      properties: [`Combo Starter`, `All`],
    },
    {
      name: `Ness`,
      series: [`Mother`],
      img: `https://ssb.wiki.gallery/images/thumb/8/82/Ness_SSBU.png/1200px-Ness_SSBU.png`,
      price: 100.0,
      properties: [`Floaty`, `Projectiles`, `All`],
    },
    {
      name: `Captain Falcon`,
      series: [`F-Zero`],
      img: `https://ssb.wiki.gallery/images/thumb/d/da/Captain_Falcon_SSBU.png/1200px-Captain_Falcon_SSBU.png`,
      price: 20.0,
      properties: [`Heavy`, `All`],
    },
    {
      name: `Jigglypuff`,
      series: [`Pokemon`],
      img: `https://ssb.wiki.gallery/images/thumb/6/6a/Jigglypuff_SSBU.png/1200px-Jigglypuff_SSBU.png`,
      price: 40.0,
      properties: [`Floaty`, `All`],
    },
  ],
};

export { roster };
